spring:
    application:
        name: crm-api

# ** HEROKU **
    datasource:
        url: jdbc:postgresql://ec2-54-83-49-109.compute-1.amazonaws.com:5432/d7d46ujr3305mp
        platform: POSTGRESQL
        username: ebqxumtmukhdjh
        password: ec82eafed81d80ce95b36fe39403dd563742777d8bc709d8874cebcd08523ebe

# ** LOCAL **
#    datasource:
#        url: jdbc:postgresql://localhost:5432/crmapi
#        platform: POSTGRESQL
#        username: postgres
#        password: postgres

    jpa:
        hibernate:
            ddl-auto: create-drop
            dialect: org.hibernate.dialect.PostgreSQL95Dialect
            show_sql: true
        spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
        properties.hibernate.temp.use_jdbc_metadata_defaults: false


server:
    port: 8080

    servlet:
        context-path: /api