spring:
    application:
        name: crm-api

    datasource:
        url: jdbc:postgresql://localhost:5432/crmapi
        platform: POSTGRESQL
        username: postgres
        password: postgres

    jpa:
        hibernate:
            ddl-auto: create-drop
            dialect: org.hibernate.dialect.PostgreSQL95Dialect
            show_sql: true
        spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
        properties.hibernate.temp.use_jdbc_metadata_defaults: false

server:
    port: 8080

    servlet:
        context-path: /api



#----------------------- LOCAL DB
#spring.datasource.driver-class-first_name=com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/crm
#spring.datasource.username=root
#spring.datasource.password=rootroot


#----------------------- HOST DB
#spring.datasource.url=jdbc:mysql://xk319036.mysql.tools:3306/xk319036_crmapid
#spring.datasource.username=xk319036_yolo
#spring.datasource.password=yolo